feat(HybridSolidInput): Added the grdecl input for hybrid solids.
Geode-solutions/OpenGeode-GeosciencesIO pull request #89
Opened 2023-09-06 12:05 UTC by BenPinet

2023-09-06 15:18 UTC, MelchiorSchuh commented on src/geode/geosciences_io/mesh/grdecl_input.cpp
> +                    std::getline( file_, line );
put the getline directly after the if and remove the else condition

2023-09-06 15:18 UTC, MelchiorSchuh commented on src/geode/geosciences_io/mesh/grdecl_input.cpp
> +                            geode::string_to_double( tokens[2] ) } );
create point directly ( geode::Point3D top_point{{x,y,z}}; )

2023-09-06 15:18 UTC, MelchiorSchuh commented on src/geode/geosciences_io/mesh/grdecl_input.cpp
> +                    depths_number++;
remove the second one

2023-09-06 15:18 UTC, MelchiorSchuh commented on src/geode/geosciences_io/mesh/grdecl_input.cpp
> +            const absl::FixedArray< double >& depths,
Use Span

2023-09-06 15:18 UTC, MelchiorSchuh commented on src/geode/geosciences_io/mesh/grdecl_input.cpp
> +    geode::Point3D interpolate_on_pillar(
better naming

2023-09-06 15:18 UTC, MelchiorSchuh commented on src/geode/geosciences_io/mesh/grdecl_input.cpp
> +            points[0] = interpolate_on_pillar(
builder.create_point(interpolate...)

2023-09-06 15:18 UTC, MelchiorSchuh commented on tests/mesh/test-grdecl.cpp
> +void check_solid( geode::HybridSolid3D& solid, geode::index_t nb_polyhedra )
```suggestion
void check_solid( const geode::HybridSolid3D& solid, geode::index_t nb_polyhedra )
```

2023-09-06 15:18 UTC, MelchiorSchuh commented on tests/mesh/test-grdecl.cpp
> +    auto solid = geode::load_hybrid_solid< 3 >( filename );
```suggestion
    const auto solid = geode::load_hybrid_solid< 3 >( filename );
```

2023-09-08 07:27 UTC, BotellaA requested changes

2023-09-08 07:27 UTC, BotellaA commented on src/geode/geosciences_io/mesh/grdecl_input.cpp
> +            const auto& pillars_id = cell_pillars_id( grid_coordinates );
```suggestion
            const auto pillars_id = cell_pillars_id( grid_coordinates );
```

2023-09-08 07:27 UTC, BotellaA commented on src/geode/geosciences_io/mesh/grdecl_input.cpp
> +                bottom_right_pillar ) );
```suggestion
            points[1] = interpolate_on_pillar(
                depths[2 * grid_coordinates[0] + 4 * nx_ * grid_coordinates[1]
                       + 4 * nx_ * ny_ * ( grid_coordinates[2] + 1 ) + 2 * nx_
                       + 1],
                bottom_right_pillar );
```
to do for all points

2023-09-08 07:27 UTC, BotellaA commented on src/geode/geosciences_io/mesh/grdecl_input.cpp
> +        geode::NNSearch3D::ColocatedInfo create_all_points(
```suggestion
        geode::NNSearch3D::ColocatedInfo create_points(
```

2023-09-08 07:27 UTC, BotellaA commented on src/geode/geosciences_io/mesh/grdecl_input.cpp
> +        void create_grid( absl::Span< const Pillar > pillars,
```suggestion
        void create_cells( absl::Span< const Pillar > pillars,
```

2023-09-08 07:27 UTC, BotellaA commented on src/geode/geosciences_io/mesh/grdecl_input.cpp
> +                + ( number_of_vertices_on_lines ) * ( grid_coordinates[1] + 1 );
```suggestion
                + number_of_vertices_on_lines * ( grid_coordinates[1] + 1 );
```
simplify readability

2023-09-08 07:27 UTC, BotellaA commented on tests/CMakeLists.txt
> +    find_package(OpenGeode-IO REQUIRED CONFIG)
```suggestion
```
No

2023-09-08 07:27 UTC, BotellaA commented on tests/mesh/CMakeLists.txt
> +        OpenGeode-IO::mesh
```suggestion
```

2023-09-08 07:27 UTC, BotellaA commented on tests/mesh/test-grdecl.cpp
> +#include <geode/io/mesh/common.h>
```suggestion
```

2023-09-08 07:27 UTC, BotellaA commented on tests/mesh/test-grdecl.cpp
> +        geode::IOMeshLibrary::initialize();
```suggestion
```

2023-09-08 09:32 UTC, BotellaA approved these changes

2023-09-08 09:51 UTC, merged